'use client';
import {useState} from 'react';
import {useStore} from './store';
import {Button,PageHeader,Field,Badge,Filters,Empty,Modal} from './ui';
import {advanceOrder,customer,product,date,money,sum} from '@/lib/domain';
export default function Driver(){
 const {s,change}=useStore();
 const drivers=Array.from(new Set(s.deliveries.map(d=>d.driver))).filter(Boolean);
 const [driver,setDriver]=useState(drivers[0]||'');const [tab,setTab]=useState('งานที่ต้องส่ง');
 const [selected,setSelected]=useState('');const [recipient,setRecipient]=useState('');const [note,setNote]=useState('');const [problem,setProblem]=useState('');const [checked,setChecked]=useState(false);
 const jobs=s.deliveries.filter(d=>d.driver===driver);
 const visible=jobs.filter(d=>tab==='ประวัติส่งสำเร็จ'?d.status==='จัดส่งสำเร็จ':d.status!=='จัดส่งสำเร็จ');
 const d=s.deliveries.find(d=>d.id===selected);const o=s.orders.find(o=>o.id===d?.oid);const c=o?customer(s,o.cid):null;
 const close=()=>{setSelected('');setRecipient('');setNote('');setProblem('');setChecked(false)};
 return <><PageHeader title="งานส่งของฉัน" description="ตรวจสินค้าและปลายทางก่อนออกส่ง แล้วบันทึกผลเมื่อส่งมอบให้ลูกค้า"/>
 <Field label="ทดลองเป็นพนักงานส่งของ"><select value={driver} onChange={e=>{setDriver(e.target.value);close()}}>{drivers.map(n=><option key={n}>{n}</option>)}</select></Field><p className="muted">ต้นแบบเลือกชื่อผู้ส่งเพื่อดูเฉพาะงานที่ได้รับมอบหมาย</p>
 <Filters value={tab} onChange={setTab} items={[{label:'งานที่ต้องส่ง',value:'งานที่ต้องส่ง',count:jobs.filter(d=>d.status!=='จัดส่งสำเร็จ').length},{label:'ประวัติส่งสำเร็จ',value:'ประวัติส่งสำเร็จ',count:jobs.filter(d=>d.status==='จัดส่งสำเร็จ').length}]}/>
 {!visible.length&&<Empty title="ไม่มีงานในรายการนี้" description="งานใหม่จะแสดงเมื่อร้านมอบหมายงานส่งให้ชื่อผู้ส่งที่เลือก"/>}
 <div className="driver-jobs">{visible.map(d=>{const o=s.orders.find(o=>o.id===d.oid)!;const c=customer(s,o.cid);return <article className="driver-card" key={d.id}><div className="driver-card-top"><b>{c.name}</b><Badge>{d.status}</Badge></div><p>{d.address}</p><small>{d.oid} · กำหนดส่ง {date(d.eta)}</small><p>{o.items.length} รายการ · {d.carrier}</p>{d.log.some(x=>x.startsWith('ปัญหา:'))&&d.status!=='จัดส่งสำเร็จ'&&<p className="warning-text">มีปัญหาที่แจ้งไว้ — ตรวจประวัติก่อนส่งต่อ</p>}<Button primary onClick={()=>{setSelected(d.id);setRecipient(c.name)}}>{d.status==='จัดส่งสำเร็จ'?'ดูผลส่งมอบ':'เปิดงานและดำเนินการ'}</Button></article>})}</div>
 {d&&o&&c&&<Modal title={'งานส่ง '+d.id} onClose={close}><Badge>{d.status}</Badge><h3>{c.name}</h3><p>{d.address}</p><div className="actions"><a className="text-link" href={'tel:'+c.phone}>โทรหาลูกค้า {c.phone}</a><a className="text-link" href={'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(d.address)} target="_blank" rel="noreferrer">เปิดแผนที่</a></div><p>กำหนดส่ง {date(d.eta)} · เลขติดตาม {d.tracking}</p><h3>สินค้าที่ต้องส่ง</h3>{o.items.map((i,n)=><div className="list-row" key={n}><b>{product(s,i.pid).name}</b><span>{i.qty} {product(s,i.pid).unit}</span></div>)}<p>ยอดคำสั่งซื้อ ฿{money(sum(o))} · {o.receipt?'รับชำระแล้ว':'ยังไม่มีใบเสร็จรับเงินในระบบ'}</p>
 {d.status==='รอรับสินค้า'&&<><label className="check-row"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/>ตรวจจำนวนสินค้าและรับสินค้าจากคลังครบแล้ว</label><Button primary disabled={!checked} onClick={()=>{change('ออกจัดส่งแล้ว',s=>{const job=s.deliveries.find(x=>x.id===d.id)!;if(job.status!=='รอรับสินค้า')throw Error('งานนี้ออกจัดส่งแล้ว');advanceOrder(s.orders.find(x=>x.id===job.oid)!,'กำลังจัดส่ง');job.status='กำลังจัดส่ง';job.log.push('ออกจัดส่งโดย '+driver+' · '+new Date().toLocaleString('th-TH'));});setChecked(false)}}>ออกจัดส่ง</Button></>}
 {d.status==='กำลังจัดส่ง'&&<><h3>ยืนยันส่งมอบ</h3><Field label="ชื่อผู้รับสินค้า"><input value={recipient} onChange={e=>setRecipient(e.target.value)}/></Field><Field label="หมายเหตุการส่งมอบ"><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="เช่น ส่งให้ผู้รับที่หน้าร้าน ตรวจสินค้าครบแล้ว"/></Field><label className="check-row"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/>ส่งมอบสินค้าครบและผู้รับตรวจรับแล้ว</label><Button primary disabled={!recipient.trim()||!checked} onClick={()=>{if(change('ส่งมอบสำเร็จและปิดคำสั่งซื้อแล้ว',s=>{const job=s.deliveries.find(x=>x.id===d.id)!;if(job.status!=='กำลังจัดส่ง')throw Error('งานนี้ไม่ได้อยู่ระหว่างจัดส่ง');advanceOrder(s.orders.find(x=>x.id===job.oid)!,'เสร็จสิ้น');job.status='จัดส่งสำเร็จ';job.log.push('ส่งมอบให้ '+recipient.trim()+' โดย '+driver+' · '+new Date().toLocaleString('th-TH')+(note.trim()?' · '+note.trim():''));}))close()}}>ยืนยันส่งมอบสำเร็จ</Button><hr/><h3>ส่งไม่ได้ / พบปัญหา</h3><Field label="รายละเอียดปัญหา"><textarea value={problem} onChange={e=>setProblem(e.target.value)} placeholder="เช่น ติดต่อผู้รับไม่ได้ หรือปลายทางปิด"/></Field><Button disabled={!problem.trim()} onClick={()=>{if(change('บันทึกปัญหาการส่งแล้ว งานยังคงรอส่งมอบ',s=>{s.deliveries.find(x=>x.id===d.id)!.log.push('ปัญหา: '+problem.trim()+' · '+driver+' · '+new Date().toLocaleString('th-TH'));}))setProblem('')}}>บันทึกปัญหา</Button></>}
 <h3>ประวัติงานส่ง</h3>{d.log.map((l,i)=><p className="muted" key={i}>{l}</p>)}</Modal>}
 </>;
}
