'use client';
import {useState} from 'react';
import {useStore} from './store';
import {Button,Field} from './ui';
import {money,sum} from '@/lib/domain';
export default function LinePreview(){
 const {s}=useStore();const [cid,setCid]=useState(s.customers[0]?.id||'');const [kind,setKind]=useState('ยืนยันคำสั่งซื้อ');const [draft,setDraft]=useState('');const [messages,setMessages]=useState<{cid:string;text:string;time:string}[]>([]);
 const c=s.customers.find(x=>x.id===cid);const o=s.orders.find(x=>x.cid===cid&&!['ยกเลิก','รอยืนยัน'].includes(x.status));
 const template=kind==='โปรโมชั่น'?`สวัสดีค่ะ ${c?.name}\nศาศวัต ห้องเย็น มีโปรโมชั่นสำหรับลูกค้าประจำ สนใจสินค้าแจ้งรายการและจำนวนในแชตนี้ได้เลยค่ะ\nสอบถามราคาและเงื่อนไขก่อนสั่งซื้อได้ค่ะ`:kind==='พร้อมรับสินค้า'?`คุณลูกค้า ${c?.name}\n${o?`คำสั่งซื้อ ${o.id}`:'ตัวอย่างคำสั่งซื้อ'} จัดสินค้าเรียบร้อยแล้วค่ะ\nกรุณารอข้อความนี้หลังพนักงานยืนยันว่าจัดสินค้าครบแล้ว\nแจ้งชื่อร้านหรือเลขคำสั่งซื้อเมื่อมารับได้เลยค่ะ`:`สวัสดีค่ะ ${c?.name}\n${o?`ได้รับคำสั่งซื้อ ${o.id}\n${o.items.map(i=>`${s.products.find(p=>p.id===i.pid)?.name} ${i.qty} ${s.products.find(p=>p.id===i.pid)?.unit}`).join('\n')}\nยอดสุทธิ ฿${money(sum(o))}`:'ตัวอย่างข้อความยืนยันรายการสินค้าและยอดรวม'}\nขอบคุณที่สั่งซื้อกับศาศวัต ห้องเย็นค่ะ`;
 const text=draft||template;
 return <div className="line-demo-layout"><div><p className="notice">ตัวอย่างหน้าจอแชต ไม่มีการเชื่อมบัญชี LINE หรือส่งข้อความจริง ข้อความที่ลองส่งอยู่เฉพาะหน้าต่างนี้</p><Field label="ตัวอย่างลูกค้า"><select value={cid} onChange={e=>{setCid(e.target.value);setDraft('')}}>{s.customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="ประเภทข้อความ"><select value={kind} onChange={e=>{setKind(e.target.value);setDraft('')}}><option>ยืนยันคำสั่งซื้อ</option><option>พร้อมรับสินค้า</option><option>โปรโมชั่น</option></select></Field><Field label="ข้อความที่จะส่ง"><textarea rows={9} value={text} onChange={e=>setDraft(e.target.value)}/></Field><Button primary disabled={!text.trim()||!s.settings.connections.LINE} onClick={()=>setMessages(prev=>[...prev,{cid,text,time:new Date().toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit'})}])}>ส่งเข้าหน้าตัวอย่าง</Button>{!s.settings.connections.LINE&&<p className="inline-error">เปิดการจำลอง LINE ในหน้าตั้งค่าก่อนทดลอง</p>}<p className="muted">เลือกข้อความ แก้เนื้อหา แล้วกดส่งเพื่อดูสิ่งที่ลูกค้าจะเห็น</p></div><div className="line-phone"><div className="line-chat-header"><img src="/sasawat-logo.png" alt="โลโก้ศาศวัต"/><div><b>ศาศวัต ห้องเย็น</b><small>ตัวอย่างแชต LINE</small></div></div><div className="line-chat-body"><small className="line-date">วันนี้ · {c?.name}</small><div className="line-bubble">สวัสดีค่ะ ยินดีต้อนรับสู่ศาศวัต ห้องเย็น สอบถามสินค้าและติดตามคำสั่งซื้อได้ที่นี่ค่ะ</div>{s.messages.filter(m=>m.cid===cid&&m.channel==='LINE').map(m=><div className="line-chat-entry" key={m.id}><div className="line-bubble">{m.text}</div><small>ข้อความจากโปรโมชั่นในต้นแบบ</small></div>)}{messages.filter(m=>m.cid===cid).map((m,n)=><div className="line-chat-entry" key={n}><div className="line-bubble">{m.text}</div><small>{m.time} · ส่งจำลองแล้ว</small></div>)}<div className="line-preview-label">ตัวอย่างก่อนส่ง</div><div className="line-bubble line-draft">{text}</div></div><div className="line-chat-footer">ข้อความและรูปแบบสำหรับสาธิตเท่านั้น</div></div></div>;
}
