'use client';
import {useState} from 'react';
import {useStore} from './store';
import {PageHeader,Button,Section,DataTable,Badge,Field,Filters,SearchInput,Modal,SimpleForm,Empty} from './ui';
import {TODAY,uid,date} from '@/lib/domain';
import {Course,Enrollment,trainingData,trainingRole,trainingStatuses,saveResult} from '@/lib/training';
import {OpenForm} from './orders';
export default function Training({open,userId}:{open:OpenForm;userId?:string}) {
 const {s,role,change}=useStore(); const manager=role==='ผู้จัดการ'; const data=trainingData(s);
 const [tab,setTab]=useState('การอบรม');const [search,setSearch]=useState('');const [status,setStatus]=useState('ทั้งหมด');const [employee,setEmployee]=useState('');
 const [course,setCourse]=useState<Course|null>(null);const [editor,setEditor]=useState<Course|Partial<Course>|null>(null);const [assign,setAssign]=useState<Course|null>(null);const [record,setRecord]=useState<Enrollment|null>(null);const [error,setError]=useState('');
 const eligible=s.users.filter(u=>u.active&&(manager||trainingRole(u.role)===trainingRole(role)));
 const person=eligible.find(u=>u.id===employee)||eligible[0];
 const mine=userId?data.enrollments.filter(e=>e.user===userId):manager?data.enrollments:data.enrollments.filter(e=>e.user===person?.id);
 const rows=mine.filter(e=>(status==='ทั้งหมด'||e.status===status)&&[data.courses.find(c=>c.id===e.course)?.name,s.users.find(u=>u.id===e.user)?.name].join(' ').includes(search));
 const writable=(state:typeof s)=>state.trainingData||(state.trainingData=trainingData(state));
 const selected=record?data.enrollments.find(e=>e.id===record.id):undefined;
 return <><PageHeader title={manager?'การอบรม':'การอบรมของฉัน'} description={manager?'จัดหลักสูตร มอบหมาย ติดตามและบันทึกผลการอบรม':'ดูหลักสูตรที่ได้รับมอบหมาย เตรียมตัวอบรม และติดตามผลของคุณ'} actions={manager&&!userId&&<Button primary onClick={()=>setEditor({})}>สร้างหลักสูตร</Button>}/>
 {manager&&!userId?<Filters value={tab} onChange={setTab} items={['การอบรม','หลักสูตร'].map(x=>({label:x,value:x}))}/>:!userId&&<Field label="ดูตัวอย่างพนักงานในบทบาทนี้"><select value={person?.id||''} onChange={e=>setEmployee(e.target.value)}>{eligible.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></Field>}
 {!manager&&!person&&<Empty title="ยังไม่มีพนักงานในบทบาทนี้" description="ผู้จัดการเพิ่มพนักงานและมอบหมายหลักสูตรได้"/>}
 {(tab==='การอบรม'||!manager)&&<><div className="toolbar"><SearchInput value={search} onChange={setSearch} placeholder="ค้นหาหลักสูตรหรือพนักงาน"/></div><Filters value={status} onChange={setStatus} items={['ทั้งหมด',...trainingStatuses].map(x=>({label:x,value:x,count:mine.filter(e=>x==='ทั้งหมด'||e.status===x).length}))}/><DataTable rows={rows} empty={<Empty title="ไม่มีรายการอบรมในกลุ่มนี้"/>} columns={[{label:'หลักสูตร / พนักงาน',cell:e=><><button className="customer-name" onClick={()=>{setRecord(e);setError('')}}>{data.courses.find(c=>c.id===e.course)?.name}</button><small>{s.users.find(u=>u.id===e.user)?.name}</small></>},{label:'กำหนดเสร็จ',cell:e=>date(e.due)},{label:'สถานะ',cell:e=><Badge>{e.status}</Badge>},{label:'คะแนน',cell:e=>e.score===null?'ยังไม่ประเมิน':e.score+'/100'},{label:'ทบทวนครั้งถัดไป',cell:e=>e.review?date(e.review):'—'},{label:'',cell:e=><Button small onClick={()=>{setRecord(e);setError('')}}>ดูรายละเอียด</Button>}]}/></>}
 {manager&&tab==='หลักสูตร'&&<DataTable rows={data.courses} columns={[{label:'หลักสูตร',cell:c=><button className="customer-name" onClick={()=>setCourse(c)}>{c.name}</button>},{label:'สำหรับ',cell:c=>c.role},{label:'วันอบรม / ผู้สอน',cell:c=><>{date(c.date)}<small>{c.instructor}</small></>},{label:'ผู้เข้าอบรม',cell:c=>data.enrollments.filter(e=>e.course===c.id).length+' คน'},{label:'',cell:c=><div className="actions"><Button small onClick={()=>setEditor(c)}>แก้ไข</Button><Button small onClick={()=>{setAssign(c);setError('')}}>มอบหมาย</Button></div>}]}/>}
 {manager&&tab==='พนักงาน'&&<><Button onClick={()=>open('user')}>เพิ่มพนักงาน</Button><DataTable rows={s.users} columns={[{label:'พนักงาน',cell:u=><b>{u.name}</b>},{label:'หน้าที่',cell:u=>u.role},{label:'สถานะ',cell:u=>u.active?'พร้อมใช้งาน':'พักการใช้งาน'},{label:'การอบรม',cell:u=>{const a=data.enrollments.filter(e=>e.user===u.id);return `ผ่าน ${a.filter(e=>e.status==='ผ่าน').length}/${a.length} หลักสูตร`}},{label:'',cell:u=><div className="actions"><Button small onClick={()=>{setEmployee(u.id);setTab('การอบรม');setSearch(u.name)}}>ประวัติอบรม</Button><Button small onClick={()=>open('user',u.id)}>แก้ไขพนักงาน</Button></div>}]}/></>}
 {course&&<Modal title={course.name} onClose={()=>setCourse(null)}><p>{course.objective}</p><p>ผู้สอน {course.instructor} · {date(course.date)} · {course.place}</p><Section title="หัวข้อการเรียน"><ol>{course.topics.split('\n').filter(Boolean).map((t,n)=><li key={n}>{t}</li>)}</ol></Section>{course.material?<a href={course.material} target="_blank" rel="noreferrer">เปิดเอกสารประกอบ</a>:<p className="muted">ยังไม่ได้แนบเอกสารประกอบ</p>}<p>ทบทวนทุก {course.reviewDays} วัน</p></Modal>}
 {manager&&editor&&<Modal title={editor.id?'แก้ไขหลักสูตร':'สร้างหลักสูตร'} onClose={()=>setEditor(null)}><SimpleForm onCancel={()=>setEditor(null)} onSubmit={f=>{if(f.material&&!/^https:\/\//i.test(f.material))throw Error('ลิงก์เอกสารต้องเริ่มด้วย https://');if(change('บันทึกหลักสูตรแล้ว',state=>{const d=writable(state);const c={id:editor.id||uid('COURSE'),name:f.name.trim(),objective:f.objective,topics:f.topics,material:f.material,instructor:f.instructor,date:f.date,place:f.place,role:f.role,reviewDays:Number(f.review)};if(editor.id)Object.assign(d.courses.find(x=>x.id===editor.id)!,c);else d.courses.push(c)}))setEditor(null)}}><Field label="ชื่อหลักสูตร" required><input name="name" defaultValue={editor.name} required/></Field><Field label="วัตถุประสงค์" required><textarea name="objective" defaultValue={editor.objective} required/></Field><Field label="หัวข้อการเรียน (บรรทัดละหัวข้อ)" required><textarea name="topics" rows={4} defaultValue={editor.topics} required/></Field><Field label="ลิงก์เอกสารประกอบ"><input name="material" type="url" defaultValue={editor.material} placeholder="https://..."/></Field><Field label="สำหรับบทบาท"><select name="role" defaultValue={editor.role||'ทุกบทบาท'}>{['ทุกบทบาท','ฝ่ายขาย','คลังสินค้า','ผู้ดูแลห้องเย็น','ผู้จัดการ'].map(x=><option key={x}>{x}</option>)}</select></Field><div className="form-grid"><Field label="ผู้สอน" required><input name="instructor" defaultValue={editor.instructor} required/></Field><Field label="วันอบรม" required><input name="date" type="date" defaultValue={editor.date||TODAY} required/></Field><Field label="สถานที่" required><input name="place" defaultValue={editor.place||'สาขามุกดาหาร'} required/></Field><Field label="ทบทวนทุก (วัน)" required><input name="review" type="number" min="1" max="3650" defaultValue={editor.reviewDays||180} required/></Field></div></SimpleForm></Modal>}
 {manager&&assign&&<Modal title={'มอบหมาย · '+assign.name} onClose={()=>setAssign(null)}><SimpleForm onCancel={()=>setAssign(null)} onSubmit={f=>{const users=s.users.filter(u=>f['user-'+u.id]);if(!users.length)throw Error('เลือกพนักงานอย่างน้อย 1 คน');if(change('มอบหมายการอบรมแล้ว',state=>{const d=writable(state);for(const u of users){if(d.enrollments.some(e=>e.course===assign.id&&e.user===u.id))continue;d.enrollments.push({id:uid('ENROLL'),course:assign.id,user:u.id,due:f.due,status:'นัดหมายแล้ว',attendance:'ยังไม่บันทึก',score:null,note:'',review:'',history:[{time:new Date().toISOString(),user:role,text:'มอบหมายการอบรม'}]})}}))setAssign(null)}}><Field label="กำหนดเรียนให้เสร็จ" required><input name="due" type="date" defaultValue={assign.date} required/></Field><p>รายชื่อที่ตรงกับบทบาทของหลักสูตร รายการที่มอบหมายแล้วจะไม่สร้างซ้ำ</p>{s.users.filter(u=>u.active&&(assign.role==='ทุกบทบาท'||trainingRole(u.role)===assign.role)).map(u=>{const exists=data.enrollments.some(e=>e.course===assign.id&&e.user===u.id);return <label className="check-row" key={u.id}><input type="checkbox" name={'user-'+u.id} disabled={exists}/>{u.name} · {u.role}{exists?' · มอบหมายแล้ว':''}</label>})}</SimpleForm></Modal>}
 {selected&&<Modal title={data.courses.find(c=>c.id===selected.course)?.name||'รายละเอียดการอบรม'} onClose={()=>setRecord(null)}><p><b>{s.users.find(u=>u.id===selected.user)?.name}</b> · <Badge>{selected.status}</Badge></p><p>กำหนดเสร็จ {date(selected.due)} · {selected.attendance}</p><Button onClick={()=>{setCourse(data.courses.find(c=>c.id===selected.course)!);setRecord(null)}}>ดูหัวข้อและเอกสาร</Button>
 {!manager&&<><p>คะแนน {selected.score===null?'ยังไม่ประเมิน':selected.score+'/100'} · ผ่านตั้งแต่ 80 คะแนน</p><p>{selected.note||'ยังไม่มีหมายเหตุจากผู้สอน'}</p>{selected.status==='ต้องอบรม'&&<Button primary onClick={()=>change('ยืนยันนัดหมายอบรมแล้ว',state=>{const e=writable(state).enrollments.find(x=>x.id===selected.id)!;e.status='นัดหมายแล้ว';e.history.unshift({time:new Date().toISOString(),user:person?.name||role,text:'ยืนยันนัดหมายอบรม'})})}>ยืนยันนัดหมาย</Button>}{selected.status==='นัดหมายแล้ว'&&<Button primary onClick={()=>change('แจ้งเข้าอบรมแล้ว รอผู้สอนประเมิน',state=>{const e=writable(state).enrollments.find(x=>x.id===selected.id)!;e.status='รอประเมิน';e.history.unshift({time:new Date().toISOString(),user:person?.name||role,text:'แจ้งเข้าอบรมแล้ว รอประเมิน'})})}>แจ้งว่าเข้าอบรมแล้ว</Button>}</>}
 {manager&&<SimpleForm key={selected.id+'-'+selected.history.length} label={selected.attendance==='ยังไม่บันทึก'?'บันทึกผลการอบรม':'แก้ไขผลการอบรม'} onSubmit={f=>{if(change('บันทึกผลการอบรมแล้ว',state=>saveResult(state,selected.id,{attendance:f.attendance,score:f.score===''?null:Number(f.score),note:f.note,reason:f.reason||''},role)))setRecord(null)}}><Field label="การเข้าอบรม" required><select name="attendance" defaultValue={selected.attendance==='ขาดอบรม'?'ขาดอบรม':'เข้าอบรม'}><option>เข้าอบรม</option><option>ขาดอบรม</option></select></Field><Field label="คะแนน (0–100) · ผ่านตั้งแต่ 80"><input name="score" type="number" min="0" max="100" defaultValue={selected.score??''}/></Field><Field label="หมายเหตุ / สิ่งที่ต้องทบทวน"><textarea name="note" defaultValue={selected.note}/></Field>{selected.attendance!=='ยังไม่บันทึก'&&<Field label="เหตุผลที่แก้ไขผลเดิม" required><textarea name="reason" required/></Field>}</SimpleForm>}
 {selected.review&&<p>ทบทวนครั้งถัดไป {date(selected.review)}</p>}<Section title="ประวัติรายการ">{selected.history.length?selected.history.map((h,n)=><div className="list-row" key={n}><small>{new Date(h.time).toLocaleString('th-TH-u-ca-gregory')}</small><span>{h.user} · {h.text}</span></div>):<p className="muted">ยังไม่มีการบันทึกผล</p>}</Section></Modal>}
 </>;
}
